podspec: RouteComposer.podspec
clean: true
author: HBC Tech
author_url: https://tech.hbc.com
output: docs
documentation: ./*.md
theme: fullwidth

custom_categories:
  - name: Core Entities
    children:
      - Router
      - RoutingError
      - DestinationStep
      - Finder
      - Factory
      - ContainerFactory
      - Action
      - ContainerAction
      - RoutingResult

  - name: Tasks
    children:
      - RoutingInterceptor
      - ContextTask
      - PostRoutingTask

  - name: Assemblies
    children:
      - StepAssembly
      - ContainerStepAssembly
      - SwitchAssembly
      - ChainAssembly
      - CompleteFactoryAssembly

  - name: Additional Assemblies
    children:
      - SingleStep
      - SingleContainerStep

  - name: Factories
    children:
      - ClassFactory
      - StoryboardFactory
      - FinderFactory
      - NavigationControllerFactory
      - TabBarControllerFactory
      - SplitControllerFactory
      - NilFactory

  - name: Finders
    children:
      - StackIteratingFinder
      - ClassFinder
      - InstanceFinder
      - NilFinder

  - name: Steps
    children:
      - GeneralStep
      - NavigationControllerStep
      - TabBarControllerStep
      - SplitControllerStep

  - name: UIViewController's protocols
    children:
      - RoutingInterceptable
      - ContainerViewController

  - name: General Actions
    children:
      - GeneralAction

  - name: Logging
    children:
      - Logger
      - LogMessage

  - name: Extras
    children:
      - Destination
      - AnyDestination
      - InlineInterceptor
      - InlineContextTask
      - InlinePostTask
      - NavigationDelayingInterceptor
      - SingleNavigationRouter
      - PresentingFinder
      - ContextSettingTask
      - ContextAccepting
      - ClassWithContextFinder
      - ContextChecking
      - DismissalMethodProvidingContextTask
      - Dismissible
      - DismissibleWithRuntimeStorage
      - DetailsNavigationFinder
      - CATransaction

  - name: Deprecated
    children:
      - XibFactory
      - ClassNameFactory
