podspec: RouteComposer.podspec
clean: true
author: HBC Tech
author_url: https://tech.hbc.com
output: Documentation/API
documentation: ./*.md

custom_categories:
  - name: Core Entities
    children:
      - Router
      - DestinationStep
      - Finder
      - AbstractFactory
      - Factory
      - Container
      - Action
      - ContainerAction
      - RoutingInterceptor
      - ContextTask
      - PostRoutingTask
      - RoutingError

  - name: Assemblies
    children:
      - StepAssembly
      - ContainerStepAssembly
      - SwitchAssembly
      - ChainAssembly
      - CompleteFactoryAssembly

  - name: Factories
    children:
      - XibFactory
      - StoryboardFactory
      - ClassNameFactory
      - FinderFactory
      - NavigationControllerFactory
      - TabBarControllerFactory
      - SplitControllerFactory
      - NilFactory

  - name: Finders
    children:
      - StackIteratingFinder
      - ClassFinder
      - ClassWithContextFinder
      - InstanceFinder
      - NilFinder

  - name: Steps
    children:
      - SingleStep
      - SingleContainerStep
      - GeneralStep
      - NavigationControllerStep
      - TabBarControllerStep
      - SplitControllerStep

  - name: Resulting Enums
    children:
      - RoutingResult
      - ActionResult
      - InterceptorResult

  - name: UIViewController's protocols
    children:
      - RoutingInterceptable
      - ContainerViewController